TOP = ../..
include $(TOP)/mk/boilerplate.mk

SRC_DEPS = binary bytestring array parallel primitive transformers mtl ghc-prim random

ALL_DIRS += Random SamplerMonad Scene

include $(TOP)/mk/target.mk

